<?php

namespace MonApiBundle\Repository;

/**
 * annonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAnnonce()
    {
        $time = new \DateTime();
        $time->modify('-10 day');
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.date > :time')
            ->setParameter('time', $time)
            ->orderBy('a.date', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
